### ISSUE TITLE
API Limit

### ISSUE THREAD

**Issue by djekl** [mikeholmesuk/lennox#1]
The API limit, current usage, and reset time is returned as headers with the response, you should have something available after a call is made to see this information.

**Comment by mikeholmesuk** [comment]
Hi @djekl. That's a good suggestion. I'll probably have to change the return object to include those but I don't think that's a bad thing at this point. Thanks for the suggestion - I'll push something around that soon.

**Comment by djekl** [comment]
@mikeholmesuk if you dont have this available, then users will attempt to make call after call against my service and wont know when to wait unit

**Comment by mikeholmesuk** [comment]
I've made some amendments so that the `ratelimit` header values are available in the return object. I've updated the README to reflect this as well.

**Comment by mikeholmesuk** [comment]
Response object now looks like this:

```
{ data: <object>,
  ratelimit_limit: <integer>,
  ratelimit_remaining: <integer>,
  ratelimit_reset: <integer> 
}
```
Which I'm happy enough that it resolves the issue. @djekl if you could confirm that you're happy that the above is now included I'll close the issue.

**Comment by djekl** [comment]
Yeah, thats perfect, this way users have a clear understanding of the rate limits, and should hopefully respect them. Thank you!
